### ISSUE TITLE
Carthage build error

### ISSUE THREAD

**Issue by kolisko** [naoty/SwiftCSV#49]
I am trying to build master using Carthage (Xcode8).
### Here is my Cartfile

github "naoty/SwiftCSV" "master"
### The output of the build

1 Michal-MBP:ewaycrm kolisko$ carthage update SwiftCSV --platform iOS
**\* Fetching SwiftCSV
**\* Checking out SwiftCSV at "061e595c010b97a0af94c07afb26579a2812021c"
**\* xcodebuild output can be found in /var/folders/cw/kw49vrmn5nx8scdvskyd2rqw0000gn/T/carthage-xcodebuild.hT6qd8.log
**\* Building scheme "SwiftCSV" in SwiftCSV.xcodeproj
*\* CLEAN FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
warning: no umbrella header found for target 'SwiftCSV', module map will not be generated
warning: no umbrella header found for target 'SwiftCSV', module map will not be generated
A shell task (/usr/bin/xcrun xcodebuild -project /Users/kolisko/xcode/ewaycrm/Carthage/Checkouts/SwiftCSV/SwiftCSV.xcodeproj -scheme SwiftCSV -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* CLEAN FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)

1 Michal-MBP:ewaycrm kolisko$

**Comment by grantkemp** [comment]
@kolisko did you manage to resolve this?

**Comment by grantkemp** [comment]
closing issue as no response.

**Comment by cmavromoustakos** [comment]
I am getting the same error:

`[ cmavromoustakos ~/Sandbox/imarch-backend master ] ✔ carthage build --no-skip-current                                                                                 ☹ ruby-2.3.1
*** xcodebuild output can be found in /var/folders/5m/_rgqzsr90g35fp99z65crzth0000gn/T/carthage-xcodebuild.ZX6zmb.log
*** Building scheme "SwiftCSV" in SwiftCSV.xcodeproj
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
warning: no umbrella header found for target 'SwiftCSV', module map will not be generated
warning: no umbrella header found for target 'SwiftCSV', module map will not be generated
A shell task (/usr/bin/xcrun xcodebuild -project /Users/cmavromoustakos/Sandbox/imarch-backend/Carthage/Checkouts/SwiftCSV/SwiftCSV.xcodeproj -scheme SwiftCSV -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)`

**Comment by cmavromoustakos** [comment]
Looks like the issue is I need to enable Use Legacy Swift version based on output log:

`=== CLEAN TARGET SwiftCSV OF PROJECT SwiftCSV WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
warning: no umbrella header found for target 'SwiftCSV', module map will not be generated

=== BUILD TARGET SwiftCSV OF PROJECT SwiftCSV WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
warning: no umbrella header found for target 'SwiftCSV', module map will not be generated

`
